schema_version: 1

context:
  version: "1.17.0"

recipe:
  name: gtest-split
  version: ${{ version }}

source:
  url: https://github.com/google/googletest/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 65fab701d9829d38cb77c14acdc431d2108bfdbf8979e40eb8ae567edf10b27c

build:
  number: 2

outputs:
  - package:
      name: gtest
    build:
      script:
        file: build-gtest
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - ninja
      run_exports:
        - ${{ pin_subpackage('gtest', upper_bound='x.x.x') }}
      run_constraints:
        - gmock ==${{ version }}
    tests:
      - package_contents:
          include:
            - gtest/gtest.h
            - gmock/gmock.h
          lib:
            - gtest
            - gtest_main
            - gmock
            - gmock_main
          files:
            not_exists:
              - if: unix
                then:
                  - lib/libgtest.a
                  - lib/libgtest_main.a
                  - lib/libgmock.a
                  - lib/libgmock_main.a
      - if: unix and target_platform != "linux-riscv64"
        then:
          script:
            - for lib in gtest gtest_main gmock gmock_main; do pkg-config --print-errors --exact-version "$PKG_VERSION" "$lib"; done
          requirements:
            run:
              - pkg-config
      - if: win
        then:
          script:
            - pkg-config --print-errors --exact-version "%PKG_VERSION%" gtest
            - pkg-config --print-errors --exact-version "%PKG_VERSION%" gtest_main
            - pkg-config --print-errors --exact-version "%PKG_VERSION%" gmock
            - pkg-config --print-errors --exact-version "%PKG_VERSION%" gmock_main
          requirements:
            run:
              - pkg-config

  # Empty wrapper for compatibility with the previous output separation.
  - package:
      name: gmock
    requirements:
      host:
        - ${{ pin_subpackage('gtest', exact=True) }}
      run:
        - ${{ pin_subpackage('gtest', exact=True) }}
    tests:
      - script:
          - echo "Tested in the gtest output"

about:
  homepage: https://github.com/google/googletest
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Google's C++ test framework

extra:
  recipe-maintainers:
    - SylvainCorlay
    - scopatz
    - wesm
    - marcelotrevisani
    - xhochy
    - h-vetinari
  feedstock-name: gtest
